# Generated by Django 3.0.11 on 2021-01-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210108_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('course', 'slug')},
        ),
    ]
