# Generated by Django 3.0.11 on 2021-01-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210113_0004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('course', 'title'), ('course', 'slug')},
        ),
    ]
